### PR TITLE
Event rewrite I said i was gonna do forever ago. Hope it doesnt break much.

### PR DESCRIPTION
**Pull request by The-Forecaster**
made a (semi) custom event bus implemented it. I pasted some of the event bus from alpine but a lot of it is copied from my kotlin event bus.

With this we won't have to depend on alpine and well have better compatibility.

### CODE REVIEW

**Comment by srgantmoomoo** [comment]
Debatable.

**Comment by srgantmoomoo** [comment]
Why would postman need a new event bus. Especially when a lot of it is paste lol

**Comment by The-Forecaster** [comment]
mostly so we aren't using an old version of alpine and the problems that come wherein

**Comment by srgantmoomoo** [comment]
> mostly so we aren't using an old version of alpine and the problems that come wherein

id rather just update to a newer version of alpine.

**Comment by srgantmoomoo** [comment]
:/

**Pull request closed without merging**
