### PR TITLE
Srgantmoomoo master

### PR DESCRIPTION
**Pull request by The-Forecaster**

### CODE REVIEW

**Comment by The-Forecaster** [comment]
sorry git targeted this repo instead of my fork for the pr

**Comment by TwoThreeTwo** [comment]
What the fuck? You did 20 commits of just adding THIS statements and removing spaces

**Comment by TwoThreeTwo** [comment]
Ya might as well do File -> Reformat Code -> select every box and then click OK then make a git repo

**Comment by TwoThreeTwo** [comment]
*RightClick

**Comment by The-Forecaster** [comment]
lol

**Comment by srgantmoomoo** [comment]
> lol

bit of an L pull request ngl. and ur last one totally bricked some things in the client.

**Comment by TwoThreeTwo** [comment]
Yeah, I lost my progress with fixing ca calcs on postman after your merge. It sucks butt, I don't really remember any of it anymore 
:(

**Pull request closed without merging**
