### PR TITLE
discordRPC notification

### PR DESCRIPTION
**Pull request by TwoThreeTwo**
You don't have to merge, but I just really like having notifications whenever I start/stop discordRPC :D

### CODE REVIEW

**Comment by TwoThreeTwo** [comment]
And another thing, is the postman notification supposed to be a gray italic @postman {Message}?

**Comment by TwoThreeTwo** [comment]
Another thing, if it causes nullpointerexception lmk 
Discord: Two#6969

**Comment by srgantmoomoo** [comment]
i like it, could you use the notification module to do it instead tho, something like `NotificationModule.INSTANCE.sendNoti("starting discordRPC... :)");`... the color may just be grey for now but ill do something with noti colors in a little bit so you dont have to do anything with it just yet.

...as seen [here](https://github.com/srgantmoomoo/postman/blob/master/src/main/java/me/srgantmoomoo/postman/impl/modules/player/AutoGap.java)

**Comment by srgantmoomoo** [comment]
i like it, could you use the notification module to do it instead tho, something like `NotificationModule.INSTANCE.sendNoti(ChatFormatting.RED + "autoGap cannot find a golden apple in the hotbar or offhand.");`

as seen [here](https://github.com/srgantmoomoo/postman/blob/master/src/main/java/me/srgantmoomoo/postman/impl/modules/player/AutoGap.java)

> i like it, could you use the notification module to do it instead tho, something like `NotificationModule.INSTANCE.sendNoti("starting discordRPC... :)");`... the color may just be grey for now but ill do something with noti colors in a little bit so you dont have to do anything with it just yet.
> 
> ...as seen [here](https://github.com/srgantmoomoo/postman/blob/master/src/main/java/me/srgantmoomoo/postman/impl/modules/player/AutoGap.java)

also i only use a notified boolean in that module that i linked because it's in `onUpdate()`, you don't have to do that.

**Comment by srgantmoomoo** [comment]
now that i think of it, this would probably be redundant since i'll have individual notifications for each module being enabled/disabled. but eh, if u do it ill accept the pr anyways if u want lol.

**Comment by TwoThreeTwo** [comment]
I see, 

> i like it, could you use the notification module to do it instead tho, something like `NotificationModule.INSTANCE.sendNoti("starting discordRPC... :)");`... the color may just be grey for now but ill do something with noti colors in a little bit so you dont have to do anything with it just yet.
> 
> ...as seen [here](https://github.com/srgantmoomoo/postman/blob/master/src/main/java/me/srgantmoomoo/postman/impl/modules/player/AutoGap.java)

Oh yes, I didn't see those classes, should've done some exploring before I made that, welp I'll experiment a bit and see if that works I'll post here incase I do work

**Comment by TwoThreeTwo** [comment]
> now that i think of it, this would probably be redundant since i'll have individual notifications for each module being enabled/disabled. but eh, if u do it ill accept the pr anyways if u want lol.

Good point, dw about accepting it

**Comment by TwoThreeTwo** [comment]
Another thing, Chat mode in notification does nothing? Is this an issue on my end?  hud by drawing it into the hud list, but chat has nothing, has it been finished? idk if you store the different modes into separate classes

**Comment by TwoThreeTwo** [comment]
Update, checked the code, and it's related to command manager 💀

**Comment by srgantmoomoo** [comment]
hmmm it should work. you have to make sure notification module itself is toggled on, aswell as the mode being set to chat. 

in the case of autogap, to see the notification, you can set mode to always and turn on switchToGap, then if there is no gapple in ur inventory you should see the message.

**Comment by srgantmoomoo** [comment]
> hmmm it should work. you have to make sure notification module itself is toggled on, aswell as the mode being set to chat.
> 
> in the case of autogap, to see the notification, you can set mode to always and turn on switchToGap, then if there is no gapple in ur inventory you should see the message.

hud mode does not do anything as of now tho.

**Comment by TwoThreeTwo** [comment]
> hmmm it should work. you have to make sure notification module itself is toggled on, aswell as the mode being set to chat.

https://user-images.githubusercontent.com/83801755/162113420-0fe806aa-fefc-4bd9-bbb1-1112d87f423f.mp4


well, yeah notification is toggled on, mode is also set to chat, I enable a module -> no message. I tried binding a module to a keyBind and trying again, still nothing

**Comment by srgantmoomoo** [comment]
oh, yea no... module enabling and disabling does nothing rn for notifications, i have not added it yet.

**Comment by TwoThreeTwo** [comment]
oh, sorry for the bother then lol

**Comment by srgantmoomoo** [comment]
all good lol

**Pull request closed without merging**
